export const YANGON_TOWNSHIPS = [
  { en: "Ahlon", my: "အလုံ" },
  { en: "Bahan", my: "ဗဟန်း" },
  { en: "Botataung", my: "ဗိုလ်တထောင်" },
  { en: "Dagon", my: "ဒဂုံ" },
  { en: "Dagon Seikkan", my: "ဒဂုံဆိပ်ကမ်း" },
  { en: "Dawbon", my: "ဒေါပုံ" },
  { en: "East Dagon", my: "ဒဂုံမြို့သစ်အရှေ့ပိုင်း" },
  { en: "Hlaing", my: "လှိုင်" },
  { en: "Hlaingthaya", my: "လှိုင်သာယာ" },
  { en: "Insein", my: "အင်းစိန်" },
  { en: "Kamayut", my: "ကမာရွတ်" },
  { en: "Kyauktada", my: "ကျောက်တံတား" },
  { en: "Kyimyindaing", my: "ကြည့်မြင်တိုင်" },
  { en: "Lanmadaw", my: "လမ်းမတော်" },
  { en: "Latha", my: "လသာ" },
  { en: "Mayangon", my: "မရမ်းကုန်း" },
  { en: "Mingaladon", my: "မင်္ဂလာဒုံ" },
  { en: "Mingala Taungnyunt", my: "မင်္ဂလာတောင်ညွန့်" },
  { en: "North Dagon", my: "ဒဂုံမြို့သစ်မြောက်ပိုင်း" },
  { en: "North Okkalapa", my: "မြောက်ဥက္ကလာပ" },
  { en: "Pabedan", my: "ပန်းဘဲတန်း" },
  { en: "Pazundaung", my: "ပုဇွန်တောင်" },
  { en: "Sanchaung", my: "စမ်းချောင်း" },
  { en: "Seikkan", my: "ဆိပ်ကမ်း" },
  { en: "Shwepyitha", my: "ရွှေပြည်သာ" },
  { en: "South Dagon", my: "ဒဂုံမြို့သစ်တောင်ပိုင်း" },
  { en: "South Okkalapa", my: "တောင်ဥက္ကလာပ" },
  { en: "Tamwe", my: "တာမွေ" },
  { en: "Thaketa", my: "သာကေတ" },
  { en: "Thingangyun", my: "သင်္ဃန်းကျွန်း" },
  { en: "Yankin", my: "ရန်ကင်း" }
];
